name: CI

on:
  push:
    branches: 
      - release

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Setup node
      uses: actions/setup-node@v1.1.0
    - name: Install app dependencies
      run: npm install
    - name: Build app static files
      run: npm run build
    - name: Deploy to Master
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: dist

